name: ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run app in background
        run: |
          nohup gunicorn --bind 0.0.0.0:5000 app:app &
          sleep 10  # give time for the app to start

      - name: Make ZAP working directory writable
        run: sudo chmod -R a+w ${{ github.workspace }}

      - name: Run ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:5000/api/advisories/GHSA-vrq4-9hc3-cgp7'
          allow_issue_writing: false
          cmd_options: '-a -J report_json.json -w report_md.md -r report_html.html'
